# Generated by Django 5.2.3 on 2026-07-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_country',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Preferred Americas country for address search (e.g. Canada)',
                max_length=80,
            ),
        ),
    ]
