# Generated by Django 5.2.3 on 2026-08-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_provider_deletion_feedback'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='providerdeletionfeedback',
            new_name='accounts_pr_created_9482e6_idx',
            old_name='accounts_pr_created_7c2f8a_idx',
        ),
        migrations.RenameIndex(
            model_name='providerdeletionfeedback',
            new_name='accounts_pr_reason_04f798_idx',
            old_name='accounts_pr_reason_8b1e4d_idx',
        ),
    ]
