# Generated by Django 5.2.3 on 2026-09-07 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_app_last_seen_at'),
        ('businesses', '0025_subscription_ending_reminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scam', 'Scam or fraud'), ('harassment', 'Harassment or threats'), ('inappropriate', 'Inappropriate content or behavior'), ('spam', 'Spam'), ('safety', 'Safety concern'), ('other', 'Other')], max_length=32)),
                ('detail', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=16)),
                ('conversation_id', models.PositiveIntegerField(blank=True, help_text='Optional OrgCustomerConversation pk for context.', null=True)),
                ('admin_notes', models.TextField(blank=True, default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='devicepushtoken',
            new_name='accounts_de_user_id_c95c87_idx',
            old_name='accounts_de_user_id_8f2c1a_idx',
        ),
        migrations.AddField(
            model_name='chatblock',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatblock',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks_as_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatblock',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks', to='businesses.organization'),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='reported_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_reports', to='businesses.organization'),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='reported_user',
            field=models.ForeignKey(blank=True, help_text='Set when a provider reports a customer; null when a customer reports a business.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_reports_against', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_reports_filed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatblock',
            index=models.Index(fields=['organization', 'customer'], name='accounts_ch_organiz_f156c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatblock',
            constraint=models.UniqueConstraint(fields=('organization', 'customer'), name='uniq_chat_block_org_customer'),
        ),
        migrations.AddIndex(
            model_name='safetyreport',
            index=models.Index(fields=['status', '-created_at'], name='accounts_sa_status_54c4d0_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyreport',
            index=models.Index(fields=['reported_organization', '-created_at'], name='accounts_sa_reporte_cfcfb9_idx'),
        ),
    ]
