# Generated by Django 5.2.3 on 2026-09-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_safety_report_and_chat_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderTrialClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Normalized owner email that already used the Pro trial.', max_length=254, unique=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user_id_snapshot', models.PositiveIntegerField(blank=True, help_text='User pk when the trial was claimed (row may later be anonymized).', null=True)),
                ('organization_id_snapshot', models.PositiveIntegerField(blank=True, help_text='Organization pk when the trial was claimed.', null=True)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
    ]
