# Generated by Django 5.2.3 on 2026-09-16 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_legacy_drf_tokens(apps, schema_editor):
    """Keep existing SPA cookies valid after switching off one-token-per-user."""
    AuthToken = apps.get_model('accounts', 'AuthToken')
    try:
        Token = apps.get_model('authtoken', 'Token')
    except LookupError:
        return
    existing = set(AuthToken.objects.values_list('key', flat=True))
    to_create = []
    for token in Token.objects.all().iterator():
        if token.key in existing:
            continue
        to_create.append(
            AuthToken(key=token.key, user_id=token.user_id, created=token.created)
        )
        existing.add(token.key)
    if to_create:
        AuthToken.objects.bulk_create(to_create, batch_size=500)
    Token.objects.all().delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_admin_login_failure_day'),
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', 'created'], name='accounts_au_user_id_09e332_idx')],
            },
        ),
        migrations.RunPython(copy_legacy_drf_tokens, noop_reverse),
    ]
