# Generated by Django 5.2.3 on 2026-06-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_organization_service_radius_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='America/New_York', help_text='IANA timezone (e.g. America/New_York). Used for schedule hours and slot times.', max_length=64),
        ),
        migrations.AlterField(
            model_name='organization',
            name='booking_policy',
            field=models.CharField(choices=[('instant', 'Open — instant confirmation'), ('approval', 'Open — requires approval'), ('clients_only', 'By invitation only — approved customers')], default='approval', max_length=20),
        ),
    ]
