# Generated by Django 5.2.3 on 2026-07-27 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0018_organization_booking_policy_quote'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationlocation',
            new_name='businesses__organiz_8bc671_idx',
            old_name='biz_orgloc_org_active_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationlocation',
            new_name='businesses__latitud_76acca_idx',
            old_name='biz_orgloc_lat_lng_idx',
        ),
    ]
