# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0019_quote_followup_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_account_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_details_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(
                blank=True,
                default='none',
                help_text='none | trialing | active | past_due | canceled | unpaid',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(
                blank=True,
                default='free',
                help_text='free | pro_monthly | pro_yearly',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
