# Generated by Django 5.2.3 on 2026-09-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0026_organization_referral_rewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='concurrent_capacity',
            field=models.PositiveIntegerField(default=1, help_text='How many customer jobs can overlap on one time slot. Each open slot can accept this many simultaneous bookings (e.g. 2 = two appointments in parallel).'),
        ),
    ]
