"""Minimal PDF invoice generator (no third-party PDF dependency)."""

from __future__ import annotations

from decimal import Decimal
from io import BytesIO


def _escape(text: str) -> str:
    return (
        (text or '')
        .replace('\\', '\\\\')
        .replace('(', '\\(')
        .replace(')', '\\)')
    )


def _fmt_money(amount, currency: str = 'CAD') -> str:
    try:
        value = Decimal(amount or 0).quantize(Decimal('0.01'))
    except Exception:
        value = Decimal('0.00')
    return f'{currency} {value:,.2f}'


def build_invoice_pdf(invoice) -> bytes:
    """Return a simple single-page PDF for the given Invoice instance."""
    booking = invoice.booking
    org = booking.organization
    customer = booking.customer
    service_name = invoice.description or (booking.service.name if booking.service_id else 'Service')
    when = booking.start_at.strftime('%b %d, %Y %I:%M %p') if booking.start_at else ''
    ref = f'BK-{booking.pk:05d}'

    lines: list[str] = [
        'INVOICE',
        '',
        f'Invoice: {invoice.number}',
        f'Booking: {ref}',
        f'Status: {invoice.get_status_display()}',
        f'Date of service: {when}',
        '',
        f'Provider: {org.name}',
        f'Customer: {customer.full_name or customer.email}',
    ]
    if customer.email:
        lines.append(f'Email: {customer.email}')
    if booking.service_address:
        lines.append(f'Service address: {booking.service_address}')
    lines += [
        '',
        '---',
        f'Service: {service_name}',
    ]
    if invoice.pricing_type == 'range' and invoice.estimated_amount is not None:
        est = _fmt_money(invoice.estimated_amount, invoice.currency)
        if invoice.estimated_max is not None:
            est = f'{est} – {_fmt_money(invoice.estimated_max, invoice.currency)}'
        lines.append(f'Estimated: {est}')
    elif invoice.estimated_amount is not None and invoice.pricing_type != 'quote':
        lines.append(f'Catalog price: {_fmt_money(invoice.estimated_amount, invoice.currency)}')
    lines += [
        f'Amount due: {_fmt_money(invoice.amount, invoice.currency)}',
        '',
    ]
    if invoice.notes:
        lines.append(f'Notes: {invoice.notes}')
        lines.append('')
    if invoice.paid_at:
        lines.append(f'Paid on: {invoice.paid_at.strftime("%b %d, %Y")}')
    lines += [
        '',
        'Thank you for your business.',
        'Generated by Luminexa',
    ]

    # Build PDF content stream (top-down text, Helvetica 11pt)
    y = 750
    content_ops = ['BT', '/F1 11 Tf', '14 TL']
    first = True
    for line in lines:
        safe = _escape(line)
        if first:
            content_ops.append(f'1 0 0 1 50 {y} Tm ({safe}) Tj')
            first = False
        else:
            content_ops.append(f'T* ({safe}) Tj')
    content_ops.append('ET')
    stream = '\n'.join(content_ops).encode('latin-1', errors='replace')

    objects: list[bytes] = []
    objects.append(b'<< /Type /Catalog /Pages 2 0 R >>')
    objects.append(b'<< /Type /Pages /Kids [3 0 R] /Count 1 >>')
    objects.append(
        b'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] '
        b'/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>'
    )
    objects.append(b'<< /Length %d >>\nstream\n' % len(stream) + stream + b'\nendstream')
    objects.append(b'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>')

    out = BytesIO()
    out.write(b'%PDF-1.4\n')
    offsets = [0]
    for i, obj in enumerate(objects, start=1):
        offsets.append(out.tell())
        out.write(f'{i} 0 obj\n'.encode('ascii'))
        out.write(obj)
        out.write(b'\nendobj\n')
    xref_pos = out.tell()
    out.write(f'xref\n0 {len(objects) + 1}\n'.encode('ascii'))
    out.write(b'0000000000 65535 f \n')
    for off in offsets[1:]:
        out.write(f'{off:010d} 00000 n \n'.encode('ascii'))
    out.write(
        f'trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n'
        f'startxref\n{xref_pos}\n%%EOF\n'.encode('ascii')
    )
    return out.getvalue()
