# Generated by Django 5.2.3 on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_inquiry_status_and_request_messages'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerserviceinquiry',
            new_name='jobs_custom_organiz_8af64e_idx',
            old_name='jobs_custom_organiz_8f3c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='providernotification',
            new_name='jobs_provid_organiz_3946e2_idx',
            old_name='jobs_provid_organiz_8e0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='unavailableblock',
            new_name='jobs_unavai_organiz_45cde3_idx',
            old_name='jobs_unavail_org_start_idx',
        ),
        migrations.AlterField(
            model_name='bookingstatusevent',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('started', 'Started'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled'), ('no_show', 'No-show')], max_length=20),
        ),
    ]
