# Generated by Django 5.2.3 on 2026-07-27 23:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_booking_quote_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customernotification',
            new_name='jobs_custom_custome_d7cf4e_idx',
            old_name='jobs_custom_custome_7c8a1d_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount before tax. Null on legacy invoices.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
