# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_service_quote_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='platform_fee_cents',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Luminexa application fee charged on this payment (cents).',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(
                blank=True,
                default='',
                help_text='offline | stripe | …',
                max_length=32,
            ),
        ),
    ]
