# Generated by Django 5.2.3 on 2026-09-16 02:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0027_alter_organization_concurrent_capacity'),
        ('jobs', '0051_referral_rewards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='quote_questions',
            field=models.JSONField(blank=True, default=list, help_text='[{id, question, answer}] clarifying questions before / with a quote.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Fixed price'), ('range', 'Price range'), ('average', 'Typical / average price'), ('quote', 'Quote on request')], default='fixed', max_length=10),
        ),
        migrations.CreateModel(
            name='GigPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('location_address', models.TextField(blank=True, default='')),
                ('location_city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('location_state', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('location_postal_code', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geocoded from postal code for radius search', max_digits=9, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geocoded from postal code for radius search', max_digits=9, null=True)),
                ('search_radius_miles', models.DecimalField(decimal_places=1, default=25, help_text='How far from this location to search for providers', max_digits=5)),
                ('status', models.CharField(choices=[('open', 'Open for quotes'), ('quoted', 'Has quotes'), ('accepted', 'Quote accepted'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='Auto-close date (typically 30 days after creation)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gig_posts', to='businesses.businesstype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GigComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_comments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Set if author is provider staff/owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gig_comments', to='businesses.organization')),
                ('gig_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jobs.gigpost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GigPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gigs/images/%Y/%m/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gig_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jobs.gigpost')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GigQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(help_text='What this quote covers', max_length=1500)),
                ('estimated_duration_days', models.PositiveIntegerField(blank=True, help_text='How many days this job will take', null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted by customer'), ('withdrawn', 'Withdrawn by provider')], db_index=True, default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gig_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='jobs.gigpost')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_quotes', to='businesses.organization')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gig_quotes_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['price', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gigpost',
            index=models.Index(fields=['status', '-created_at'], name='jobs_gigpos_status_59b7ed_idx'),
        ),
        migrations.AddIndex(
            model_name='gigpost',
            index=models.Index(fields=['category', 'status', '-created_at'], name='jobs_gigpos_categor_c8caac_idx'),
        ),
        migrations.AddIndex(
            model_name='gigpost',
            index=models.Index(fields=['location_latitude', 'location_longitude'], name='jobs_gigpos_locatio_be2d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='gigcomment',
            index=models.Index(fields=['gig_post', 'created_at'], name='jobs_gigcom_gig_pos_627a88_idx'),
        ),
        migrations.AddIndex(
            model_name='gigquote',
            index=models.Index(fields=['gig_post', 'price'], name='jobs_gigquo_gig_pos_40194e_idx'),
        ),
        migrations.AddIndex(
            model_name='gigquote',
            index=models.Index(fields=['organization', '-created_at'], name='jobs_gigquo_organiz_82ae83_idx'),
        ),
        migrations.AddConstraint(
            model_name='gigquote',
            constraint=models.UniqueConstraint(fields=('gig_post', 'organization'), name='one_quote_per_org_per_post'),
        ),
    ]
