# Generated by Django 5.2.3 on 2026-09-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0052_alter_booking_quote_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customernotification',
            name='kind',
            field=models.CharField(choices=[('booking_confirmed', 'Booking confirmed'), ('booking_declined', 'Booking declined'), ('booking_cancelled', 'Booking cancelled'), ('booking_rescheduled', 'Booking rescheduled'), ('booking_time_change', 'Provider proposed a new time'), ('booking_reminder', 'Appointment reminder'), ('booking_completed', 'Booking completed'), ('rate_service', 'Rate your service'), ('invoice_ready', 'Invoice ready'), ('payment_confirmed', 'Payment confirmed'), ('new_message', 'New message'), ('quote_details_requested', 'Quote details requested'), ('new_gig_quote', 'New quote on your gig'), ('new_gig_comment', 'New comment on your gig'), ('gig_expired', 'Gig post expired')], max_length=40),
        ),
        migrations.AlterField(
            model_name='providernotification',
            name='kind',
            field=models.CharField(choices=[('flexi_no_slots_next_week', 'No slots open next week'), ('new_customer_booking', 'New customer booking'), ('customer_cancelled_booking', 'Customer cancelled booking'), ('customer_reschedule_request', 'Customer reschedule request'), ('quote_accepted', 'Quote accepted'), ('payment_received', 'Payment received'), ('new_message', 'New message'), ('promo_offer', 'Promo offer'), ('quote_answers_received', 'Quote answers received'), ('customer_reported_no_show', 'Customer reported no-show'), ('incomplete_job_tasks', 'Incomplete job tasks'), ('subscription_ending', 'Subscription ending'), ('new_gig_in_area', 'New gig in your area'), ('gig_quote_accepted', 'Gig quote accepted'), ('new_gig_comment', 'New comment on gig')], max_length=40),
        ),
    ]
