# Generated by Django 5.2.3 on 2026-09-16 22:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0053_gig_notification_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigquote',
            name='counter_message',
            field=models.TextField(blank=True, default='', help_text='Optional note with the customer counter-offer.', max_length=1000),
        ),
        migrations.AddField(
            model_name='gigquote',
            name='counter_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customer-proposed price awaiting provider response.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='gigquote',
            name='countered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customernotification',
            name='kind',
            field=models.CharField(choices=[('booking_confirmed', 'Booking confirmed'), ('booking_declined', 'Booking declined'), ('booking_cancelled', 'Booking cancelled'), ('booking_rescheduled', 'Booking rescheduled'), ('booking_time_change', 'Provider proposed a new time'), ('booking_reminder', 'Appointment reminder'), ('booking_completed', 'Booking completed'), ('rate_service', 'Rate your service'), ('invoice_ready', 'Invoice ready'), ('payment_confirmed', 'Payment confirmed'), ('new_message', 'New message'), ('quote_details_requested', 'Quote details requested'), ('new_gig_quote', 'New quote on your gig'), ('new_gig_comment', 'New comment on your gig'), ('gig_expired', 'Gig post expired'), ('gig_counter_declined', 'Provider declined your counter-offer')], max_length=40),
        ),
        migrations.AlterField(
            model_name='gigquote',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('countered', 'Customer counter-offer'), ('accepted', 'Accepted by customer'), ('rejected', 'Rejected by customer'), ('withdrawn', 'Withdrawn by provider')], db_index=True, default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='providernotification',
            name='kind',
            field=models.CharField(choices=[('flexi_no_slots_next_week', 'No slots open next week'), ('new_customer_booking', 'New customer booking'), ('customer_cancelled_booking', 'Customer cancelled booking'), ('customer_reschedule_request', 'Customer reschedule request'), ('quote_accepted', 'Quote accepted'), ('payment_received', 'Payment received'), ('new_message', 'New message'), ('promo_offer', 'Promo offer'), ('quote_answers_received', 'Quote answers received'), ('customer_reported_no_show', 'Customer reported no-show'), ('incomplete_job_tasks', 'Incomplete job tasks'), ('subscription_ending', 'Subscription ending'), ('new_gig_in_area', 'New gig in your area'), ('gig_quote_accepted', 'Gig quote accepted'), ('new_gig_comment', 'New comment on gig'), ('gig_quote_countered', 'Customer countered your gig bid'), ('gig_quote_rejected', 'Customer rejected your gig bid')], max_length=40),
        ),
    ]
