# Generated by Django 5.2.3 on 2026-09-16 23:06

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


GIG_MESSAGE_PREFIX = 'Accepted bid from gig post:'
CUSTOM_JOB_NAME = 'Custom job'


def repair_gig_bookings(apps, schema_editor):
    """Fix bookings that inherited a catalog service from a gig open slot."""
    CustomerServiceInquiry = apps.get_model('jobs', 'CustomerServiceInquiry')
    Service = apps.get_model('jobs', 'Service')

    inquiries = (
        CustomerServiceInquiry.objects.filter(booking_id__isnull=False)
        .filter(Q(gig_quote_id__isnull=False) | Q(message__startswith=GIG_MESSAGE_PREFIX))
        .select_related('booking', 'booking__service')
    )
    for inquiry in inquiries.iterator():
        booking = inquiry.booking
        if booking is None:
            continue
        label = (inquiry.service_label or '').strip()[:200]
        updates = []
        if label and booking.job_title != label:
            booking.job_title = label
            updates.append('job_title')

        svc = booking.service
        if svc is None or svc.name != CUSTOM_JOB_NAME:
            custom, _ = Service.objects.get_or_create(
                organization_id=booking.organization_id,
                name=CUSTOM_JOB_NAME,
                defaults={
                    'description': 'Used for custom and gig-wall bookings.',
                    'duration_minutes': 60,
                    'pricing_type': 'quote',
                    'base_price': 0,
                    'allow_request': False,
                    'fulfillment_kind': 'mobile',
                    'is_active': True,
                    'sort_order': 9999,
                },
            )
            if booking.service_id != custom.id:
                booking.service_id = custom.id
                updates.append('service')
        if updates:
            booking.save(update_fields=updates)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0054_gig_quote_counter_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='job_title',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Display title for gig/custom jobs (overrides catalog service name when set).',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name='customerserviceinquiry',
            name='gig_quote',
            field=models.ForeignKey(
                blank=True,
                help_text='Accepted gig-wall bid that created this quote inquiry, if any.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='service_inquiries',
                to='jobs.gigquote',
            ),
        ),
        migrations.RunPython(repair_gig_bookings, noop_reverse),
    ]
